using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using SwimMeetLibrary;
namespace UnitTests
{
    [TestClass]
    public class AdressStructTest
    {
        [TestMethod]
        public void Test_AClubIDAutoGenerated() // must be on top 
        {
            int expectedResult1 = 1;
            int expectedResult2 = 2;

            Club club1 = new Club();
            Club club2 = new Club();
            try
            {
                Assert.AreEqual(expectedResult1, club1.ID);
                Assert.AreEqual(expectedResult2, club2.ID);
            }
            catch
            {

                throw new Exception("Club 1 id: " + club1.ID + " Club 1 id: " + club2.ID);
            }

        }

        [TestMethod]
        public void Test_Adress_ToString()
        {
            Adress adress = new Adress("35 River St", "Toronto", "ON", "M2M 5M5");
            string expectedResult = string.Format("\n\t {0} \n\t {1} \n\t {2} \n\t {3} ", adress.Street, adress.City, adress.Province, adress.Zip);

            Assert.AreEqual(expectedResult, adress.ToString());
        }
        [TestMethod]
        public void Test_Address_CityProperty()
        {
            string expectedResult = "Toronto"; 
            Adress address = new Adress("1001 bay St", "Toronto", "ON", "M2b 3g5");
            Assert.AreEqual(expectedResult, address.City);
        }

        [TestMethod]
        public void Test_Address_StreetProperty()
        {
            string expectedResult = "1001 bay St";
            Adress address = new Adress("1001 bay St", "Toronto", "ON", "M2b 3g5");
            Assert.AreEqual(expectedResult, address.Street);
        }

        [TestMethod]
        public void Test_Address_ProvinceProperty()
        {
            string expectedResult = "ON";
            Adress addres = new Adress("1001 bay St", "Toronto", "ON", "M2b 3g5");
            Assert.AreEqual(expectedResult, addres.Province);
        }

        [TestMethod]
        public void Test_Address_ZipProperty()
        {
            string expectedResult = "M2b 3g5";
            Adress addres = new Adress("1001 bay St", "Toronto", "ON", "M2b 3g5");
            Assert.AreEqual(expectedResult, addres.Zip);
        }


      
    }
}
